### ISSUE TITLE
Type length not considered in index calculation

### ISSUE THREAD

**Issue by NickAtGit** [TapTrack/NdefLibrary#2]
I found a bug in your code. When calculating the indexes you don't take in consideration that a type has more than one character. For example a `text/vcard` has a length of 10 but you only add one. The whole code only works with single character types.

https://github.com/TapTrack/NdefLibrary/blob/6e87559f59015af11f561573a6669df749566965/NdefLibrary/Classes/NdefMessage.swift#L210

I managed to fix the bug by taking the type length into the calculation: `var idIndex = typeIndex + typeLength - 1`

**Comment by dshalaby** [comment]
@NickAtGit  Thanks again for raising this and apologies for the delay in merging this in. Look out for the pod update soon.
